name: build to public branch
on:
  push:
    branches:
      - master
      
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
          
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true
    # Deploy to local repo
      - name: Deploy
        uses: s0/git-publish-subdir-action@master
        env:
          REPO: git@github.com/justin-p/hugo-testing.git
          BRANCH: public
          FOLDER: public
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
